services:
  go-server:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      # [host port]:[container port]
      - "8080:8080"
    networks:
      - go-server-network
    environment:
      # Set to false since we are going to be using the docker-compose.yml file for environment configuration
      - LOAD_ENV_FROM_FILE=false
      # Change this to modify the HTTP listen port in the container
      - PORT=8080
      # Change this to modify the gRPC listen port in the container
      - GRPC_PORT=8081
      # Change this to update the environment
      - ENVIRONMENT=dev
      # Change this to modify whether debugging is enabled or disabled
      - DEBUG=true
      # Change this to modify the name of the service that is running
      - NAME="Go Service"
networks:
  go-server-network:
    driver: bridge