services:
  go-server:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      # [host port]:[container port]
      - "8080:8080"
    networks:
      - go-server-network
    depends_on:
      go-server-cache:
        condition: service_healthy
      go-server-db:
        condition: service_healthy
      go-server-mail:
        condition: service_healthy
    environment:
      # Set to false since we are going to be using the "env_file" option to load environment variables from a file
      # and export them to the container, not load them directly into the file-based configuration map in the service
      LOAD_ENV_FROM_FILE: false
      # Use go-db-server-secret defined in the "secrets" section below
      DATABASE_PASSWORD_FILE: /run/secrets/go-db-server-secret
      # Use go-feature-flag-server-secret defined in the "secrets" section below
      FEATURE_FLAG_SDK_KEY_FILE: /run/secrets/go-feature-flag-server-secret
      # Use go-mail-server-secret defined in the "secrets" section below
      MAIL_PASSWORD_FILE: /run/secrets/go-mail-server-secret
    env_file:
      - .env
    secrets:
      - go-db-server-secret
      - go-feature-flag-server-secret
      - go-mail-server-secret
  go-server-cache:
    image: redis:8.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - go-server-network
    healthcheck:
      test: [
        "CMD", "redis-cli", "ping",
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  go-server-db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - go-server-network
    environment:
      POSTGRES_USER: go_server_user
      POSTGRES_DB: go_server_database
      # Use go-db-server-secret defined in the "secrets" section below
      POSTGRES_PASSWORD_FILE: /run/secrets/go-db-server-secret
    secrets:
      - go-db-server-secret
    healthcheck:
      test: [
        "CMD", "pg_isready",
        "-U", "${POSTGRES_USER:-postgres}",
        "-d", "${POSTGRES_DB:-postgres}",
        "-h", "go-server-db", # Use the service name as the host, not "localhost": https://stackoverflow.com/a/78477653
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  go-server-mail:
    image: maildev/maildev:2.2.1
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web UI
    networks:
      - go-server-network
    environment:
      # Set up the default maildev SMTP user credentials so we can develop with authenticated sends
      MAILDEV_INCOMING_USER: "maildev"
      MAILDEV_INCOMING_PASS: "maildev"
    healthcheck:
      test: [
        # Use a simple SMTP command to check if the mail server is responding
        "CMD",
        "echo", "EHLO", "0.0.0.0",
        "|",
        "nc", "0.0.0.0", "1025",
      ]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  # MAKE SURE THESE FILES EXIST BEFORE STARTING THE CONTAINERS!
  go-db-server-secret:
    file: build/secrets/.env.db-password
  go-feature-flag-server-secret:
    file: build/secrets/.env.feature-flag-sdk-key
  go-mail-server-secret:
    file: build/secrets/.env.mail-password
networks:
  go-server-network:
    driver: bridge