services:
  go-server:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      # [host port]:[container port]
      - "8080:8080"
    networks:
      - go-server-network
    depends_on:
      go-server-cache:
        condition: service_healthy
      go-server-db:
        condition: service_healthy
      go-server-mail:
        condition: service_healthy
    environment:
      # Set to false since we are going to be using the "env_file" option to load environment variables from a file
      # and export them to the container, not load them directly into the file-based configuration map in the service
      LOAD_ENV_FROM_FILE: false
      # Use go-db-server-secret defined in the "secrets" section below
      DATABASE_PASSWORD_FILE: /run/secrets/go-db-server-secret
    env_file:
      - .env
    secrets:
      - go-db-server-secret
  go-server-cache:
    image: redis:8.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - go-server-network
    healthcheck:
      test: [
        "CMD", "redis-cli", "ping",
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  go-server-db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - go-server-network
    environment:
      POSTGRES_USER: go_server_user
      POSTGRES_DB: go_server_database
      # Use go-db-server-secret defined in the "secrets" section below
      POSTGRES_PASSWORD_FILE: /run/secrets/go-db-server-secret
    secrets:
      - go-db-server-secret
    healthcheck:
      test: [
        "CMD", "pg_isready",
        "-U", "${POSTGRES_USER:-postgres}",
        "-d", "${POSTGRES_DB:-postgres}",
        "-h", "go-server-db", # Use the service name as the host, not "localhost": https://stackoverflow.com/a/78477653
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  go-server-mail:
    # This image hasn't been updated in a while, so we use a specific SHA digest to ensure consistent builds.
    # This SHA digest was what "latest" pointed to as of January 4, 2026.
    image: schickling/mailcatcher@sha256:55ed289525a565f7587b138a423705267eb34eda1ec8d35acd6dc7966a933e84
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web UI
    networks:
      - go-server-network
    healthcheck:
      test: [
        # Use a simple SMTP command to check if the mail server is responding
        "CMD",
        "echo", "EHLO", "0.0.0.0",
        "|",
        "nc", "0.0.0.0", "1025",
      ]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  go-db-server-secret:
    file: .env.db-password # MAKE SURE THIS FILE EXISTS BEFORE STARTING THE CONTAINERS!
networks:
  go-server-network:
    driver: bridge